/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlthuvien.view;

import com.qlthuvien.dao.TaiKhoanDao;
import static com.qlthuvien.dao.TaiKhoanDao.tklogin;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private JPanel qlBanSachJPanel = new QLBanSachJPanel();
    private JPanel qlSachJPanel = new QLSachJPanel();
    private JPanel qlNhapSachJPanel = new QLNhapSachJPanel();
    private JPanel qlMuonTraSachJPanel = new QLMuonSachJPanel();
    private JPanel qlTraSachJPanel = new QLTraSachJPanel();
    private JPanel qlTaiKhoanJPanel = new QLTaiKhoanJPanel();
    private JPanel qlDocGiaJPanel = new QLDocGiaJPanel();
    private JPanel qlNhaCungCapJPanel = new QLNhaCungCapJPanel();
    private JPanel thongKeJPanel = new ThongKeJPanel();
    private TaiKhoanDao  taiKhoanDao ;
    public MainJFrame() {
        initComponents();
        taiKhoanDao = new TaiKhoanDao();
        labelTenTK.setText(taiKhoanDao.getTK());
    }
    
    
    private void AnPanel(){
        this.qlBanSachJPanel.setVisible(false);
        this.qlDocGiaJPanel.setVisible(false);
        this.qlMuonTraSachJPanel.setVisible(false);
        this.qlTraSachJPanel.setVisible(false);
        this.qlNhapSachJPanel.setVisible(false);
        this.qlSachJPanel.setVisible(false);
        this.qlTaiKhoanJPanel.setVisible(false);
        this.qlNhaCungCapJPanel.setVisible(false);
        this.thongKeJPanel.setVisible(false);
    }
    
    private void XoaMauButton(){
        btQLMuonTraSach.setBackground(Color.white);
  
        btQLTraSach.setBackground(Color.white);
  
        btQLBanSach.setBackground(Color.white);
      
        btQLSach.setBackground(Color.white);
      
        btQLNhapSach.setBackground(Color.white);
             
        btQLTaiKhoan.setBackground(Color.white);
        
        btThongKe.setBackground(Color.white);
        
        btQLNCC.setBackground(Color.white);
        
        
       
    }
    private void HienThiPanel(JPanel panel){
        AnPanel();
        panel.setSize(1050,620);
	panel.setLocation(260, 60);
	this.getContentPane().add(panel);
        panel.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btQLMuonTraSach = new javax.swing.JButton();
        btQLBanSach = new javax.swing.JButton();
        btQLSach = new javax.swing.JButton();
        btQLNhapSach = new javax.swing.JButton();
        btQLTaiKhoan = new javax.swing.JButton();
        btQLTraSach = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        btQLNCC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btDoimk = new javax.swing.JButton();
        labelTenTK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btQLMuonTraSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLMuonTraSach.setText("Quản lý mượn sách");
        btQLMuonTraSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLMuonTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLMuonTraSachActionPerformed(evt);
            }
        });

        btQLBanSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLBanSach.setText("Quản lý bán sách");
        btQLBanSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLBanSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLBanSachActionPerformed(evt);
            }
        });

        btQLSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLSach.setText("Quản lý sách");
        btQLSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLSachActionPerformed(evt);
            }
        });

        btQLNhapSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLNhapSach.setText("Quản lý nhập sách");
        btQLNhapSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLNhapSachActionPerformed(evt);
            }
        });

        btQLTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLTaiKhoan.setText("Quản lý tài khoản");
        btQLTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLTaiKhoanActionPerformed(evt);
            }
        });

        btQLTraSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLTraSach.setText("Quản lý trả sách");
        btQLTraSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLTraSachActionPerformed(evt);
            }
        });

        btThongKe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btThongKe.setText("Thống kê");
        btThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        btQLNCC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btQLNCC.setText("Quản lý Nhà cung cấp");
        btQLNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQLNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btQLNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQLMuonTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(btQLBanSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQLSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQLNhapSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQLTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btQLMuonTraSach, btQLTraSach});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLMuonTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLTraSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLBanSach, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLNhapSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQLTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btQLBanSach, btQLMuonTraSach, btQLNhapSach, btQLSach, btQLTaiKhoan, btQLTraSach});

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý thư viện");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Đăng xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btDoimk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btDoimk.setText("Đổi mật khẩu");
        btDoimk.setMaximumSize(new java.awt.Dimension(103, 27));
        btDoimk.setMinimumSize(new java.awt.Dimension(103, 27));
        btDoimk.setPreferredSize(new java.awt.Dimension(103, 27));
        btDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoimkActionPerformed(evt);
            }
        });

        labelTenTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenTK.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(labelTenTK))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(labelTenTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 715, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQLBanSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLBanSachActionPerformed
        // TODO add your handling code here:
        
        XoaMauButton();
        btQLBanSach.setBackground(Color.CYAN);
        HienThiPanel(qlBanSachJPanel);
     
    }//GEN-LAST:event_btQLBanSachActionPerformed

    private void btQLMuonTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLMuonTraSachActionPerformed
        // TODO add your handling code here:
        
        XoaMauButton();
        btQLMuonTraSach.setBackground(Color.CYAN);
        HienThiPanel(qlMuonTraSachJPanel);
    }//GEN-LAST:event_btQLMuonTraSachActionPerformed

    private void btQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLSachActionPerformed
        // TODO add your handling code here:
        
        XoaMauButton();
        btQLSach.setBackground(Color.CYAN);
        HienThiPanel(qlSachJPanel);
    }//GEN-LAST:event_btQLSachActionPerformed

    private void btQLNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLNhapSachActionPerformed
        // TODO add your handling code here:
        
        XoaMauButton();
        btQLNhapSach.setBackground(Color.CYAN);
        HienThiPanel(qlNhapSachJPanel);
    }//GEN-LAST:event_btQLNhapSachActionPerformed

    private void btQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLTaiKhoanActionPerformed
        // TODO add your handling code here:
        if(TaiKhoanDao.loaitklogin){
            XoaMauButton();
            btQLTaiKhoan.setBackground(Color.CYAN);
            HienThiPanel(qlTaiKhoanJPanel);
        }
        else{
            this.qlTaiKhoanJPanel.setVisible(false);
            JOptionPane.showMessageDialog(null, "Chức năng này không dành cho user","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btQLTaiKhoanActionPerformed

    private void btQLTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLTraSachActionPerformed
        // TODO add your handling code here:
        
        XoaMauButton();
        btQLTraSach.setBackground(Color.CYAN);
        HienThiPanel(qlTraSachJPanel);
    }//GEN-LAST:event_btQLTraSachActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        // TODO add your handling code here:
        XoaMauButton();
        btThongKe.setBackground(Color.CYAN);
        HienThiPanel(thongKeJPanel);
    }//GEN-LAST:event_btThongKeActionPerformed

    private void btQLNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLNCCActionPerformed
        // TODO add your handling code here:
        XoaMauButton();
        btQLNCC.setBackground(Color.CYAN);
        HienThiPanel(qlNhaCungCapJPanel);
    }//GEN-LAST:event_btQLNCCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginJFrame loginfr = new LoginJFrame();
        loginfr.setBounds(400, 200, 500,400);
        loginfr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoimkActionPerformed
        DoiMk doimk = new DoiMk();
        doimk.setBounds(400, 200, 500,400);
        doimk.setVisible(true);
    }//GEN-LAST:event_btDoimkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoimk;
    private javax.swing.JButton btQLBanSach;
    private javax.swing.JButton btQLMuonTraSach;
    private javax.swing.JButton btQLNCC;
    private javax.swing.JButton btQLNhapSach;
    private javax.swing.JButton btQLSach;
    private javax.swing.JButton btQLTaiKhoan;
    private javax.swing.JButton btQLTraSach;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField labelTenTK;
    // End of variables declaration//GEN-END:variables
}
