/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlthuvien.view;

import com.qlthuvien.model.GioHang;
import com.qlthuvien.model.Sach;
import com.qlthuvien.service.SachService;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLMuonSachJPanel extends javax.swing.JPanel {

    private DefaultTableModel defaultSachTable, defaultGioTable;
    private SachService sachservice;
    private static Hashtable<String, GioHang> dsGioHang;
    private int indexHang = -1,//lay chi so hang trong bang sach
            count = 0,// so luong hang co trong gio;
            indexGiohang = -1;//chi so hang trong bang gio hang
    private XacNhanMuonJFrame xn;

    public static Hashtable<String, GioHang> getGioHang() {
        return dsGioHang;
    }

    /**
     * Creates new form QLMuonTraSachJPanel
     */
    public QLMuonSachJPanel() {
        initComponents();
        sachservice = new SachService();
        dsGioHang = new Hashtable<String, GioHang>();
        HienThiSachTable();
        KhoiTaoGioMuonTable();
       
        Thread tudonglammoi = new Thread() {
            @Override
            public void run() {
                do {

                    if (XacNhanMuonJFrame.getKetqua()) {
                        lammoi();
                        XacNhanMuonJFrame.setKetqua(false);

                    }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                } while (1 == 1);
            }
        };
        tudonglammoi.start();
    }

    public void HienThiSachTable() {
        defaultSachTable = new DefaultTableModel();
        tbSach.setModel(defaultSachTable);

        defaultSachTable.addColumn("Mã sách");
        defaultSachTable.addColumn("Tên sách");
        defaultSachTable.addColumn("Tác giả");
        defaultSachTable.addColumn("Thể loại");
        defaultSachTable.addColumn("Nhà xuất bản");
        defaultSachTable.addColumn("Giá");
        defaultSachTable.addColumn("Số lượng");
        //ngan khong cho nguoi dung edit bang
        tbSach.setDefaultEditor(Object.class, null);

        List<Sach> listSach = sachservice.getSachMuon();
        defaultSachTable.setRowCount(0);
        for (Sach sach : listSach) {
            defaultSachTable.addRow(new Object[]{
                sach.getMaSach(),
                sach.getTenSach(),
                sach.getTenTacGia(),
                sach.getTheLoai(),
                sach.getTenNxb(),
                sach.getGiaSach(),
                sach.getSoluong()
            });
        }
    }

    private void KhoiTaoGioMuonTable() {
        defaultGioTable = new DefaultTableModel() {
            //chi cho phep sua cot so luong
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return columnIndex == 2;
            }

        };
        tbGio.setModel(defaultGioTable);
        //tbGio.setDefaultEditor(Object.class, null);

        defaultGioTable.addColumn("Mã sách");
        defaultGioTable.addColumn("Tên sách");
        defaultGioTable.addColumn("Số Lượng");
        defaultGioTable.addColumn("Giá");
    }

    private List<String> Check(Hashtable<String, GioHang> gh, List<Sach> sachmuon) {
        Enumeration<String> enu = gh.keys();
        ArrayList<String> dsloi = new ArrayList<String>();
        Hashtable<String, Sach> tg = new Hashtable<String, Sach>();

        //Lay ds sach muon;
        for (Sach s : sachmuon) {
            String ms = s.getMaSach();
            tg.put(ms, s);
        }
        while (enu.hasMoreElements()) {
            String key = enu.nextElement();
            //lay gia tri ma sach, so luong trong dsGioHang
            GioHang value = gh.get(key);
            String ms = value.getMasach();
            int somuon = value.getSoluong();
            int soco = tg.get(ms).getSoluong();
            if (somuon > soco) {
                String tensach = tg.get(ms).getTenSach();
                dsloi.add(tensach);
            }
        }

        return dsloi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGio = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txMasach = new javax.swing.JTextField();
        txTensach = new javax.swing.JTextField();
        txTacgia = new javax.swing.JTextField();
        txTheloai = new javax.swing.JTextField();
        txNhaxuatban = new javax.swing.JTextField();
        btTim = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        jButton8.setText("Mượn");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMuon(evt);
            }
        });

        jButton9.setText("Tạo Mới");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaomoi(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Giỏ");

        tbGio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGio.getTableHeader().setReorderingAllowed(false);
        tbGio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGio);

        jButton7.setText("Bỏ Ra Khỏi Giỏ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorakhoigio(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(26, 26, 26)
                        .addComponent(jButton9)
                        .addGap(123, 123, 123)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setText("Tác Giả");

        jLabel5.setText("Thể Loại");

        jLabel6.setText("Nhà Xuất Bản");

        txNhaxuatban.setToolTipText("");

        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimmasach(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tìm Kiếm");

        jLabel2.setText("Mã Sách");

        jLabel3.setText("Tên Sách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txNhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btTim)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btTim))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txNhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        jButton6.setText("Thêm Vào Giỏ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemvaogio(evt);
            }
        });

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Thể loại", "Nhà xuất bản", "Giá", "Số lượng"
            }
        ));
        tbSach.getTableHeader().setReorderingAllowed(false);
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked
        // TODO add your handling code here:
        indexHang = tbSach.getSelectedRow();
    }//GEN-LAST:event_tbSachMouseClicked

    private void tbGioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGioMouseClicked
        indexGiohang = tbGio.getSelectedRow();
    }//GEN-LAST:event_tbGioMouseClicked

    private void btTimmasach(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimmasach
        // TODO add your handling code here:
        String masach = txMasach.getText();
        String tensach = txTensach.getText();
        String tentacgia = txTacgia.getText();
        String theloai = txTheloai.getText();
        String tennxb = txNhaxuatban.getText();

        List<Sach> listSach = sachservice.TimSachMuon(masach, tensach, tentacgia, tennxb, theloai);
        defaultSachTable.setRowCount(0);
        for (Sach sach : listSach) {
            defaultSachTable.addRow(new Object[]{
                sach.getMaSach(),
                sach.getTenSach(),
                sach.getTenTacGia(),
                sach.getTheLoai(),
                sach.getTenNxb(),
                sach.getGiaSach(),
                sach.getSoluong()
            });
        }
    }//GEN-LAST:event_btTimmasach

    private void btThemvaogio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemvaogio
        if (indexHang >= 0) {
            String masach = String.valueOf(tbSach.getValueAt(indexHang, 0));
            String tensach = String.valueOf(tbSach.getValueAt(indexHang, 1));
            float gia = Float.parseFloat(String.valueOf(tbSach.getValueAt(indexHang, 5)));

            GioHang gh = new GioHang(masach, tensach, 1, gia);

            if (!dsGioHang.containsKey(masach)) {
                dsGioHang.put(masach, gh);
                count++;
                defaultGioTable.addRow(new Object[]{
                    gh.getMasach(),
                    gh.getTensach(),
                    "1",
                    gh.getGia()
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn sách", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btThemvaogio

    private void btMuon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMuon
        // TODO add your handling code here:
        if (count > 0) {
            dsGioHang.clear();

            for (int i = 0; i < count; i++) {
                String masach = String.valueOf(tbGio.getValueAt(i, 0));
                String tensach = String.valueOf(tbGio.getValueAt(i, 1));
                int soluong = Integer.parseInt(String.valueOf(tbGio.getValueAt(i, 2)));
                float gia = Float.parseFloat(String.valueOf(tbGio.getValueAt(i, 3)));

                GioHang gh = new GioHang(masach, tensach, soluong, gia);

                dsGioHang.put(masach, gh);
            }

            List<String> dsloi = Check(dsGioHang, sachservice.getSachMuon());
            if (dsloi.isEmpty()) {
                xn = new XacNhanMuonJFrame();
                xn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                xn.setVisible(true);
            } else {
                String tb = "";
                for (String t : dsloi) {
                    tb += t + " ";
                }
                tb += "Khong du so luong de cho muon";
                JOptionPane.showMessageDialog(null, tb, "Thông báo", JOptionPane.ERROR_MESSAGE);
            }

        } else
            JOptionPane.showMessageDialog(null, "Chua chon sach", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btMuon
    private void lammoi() {
        HienThiSachTable();
        KhoiTaoGioMuonTable();
        indexHang = -1;
        count = 0;
        dsGioHang.clear();
    }
    private void btTaomoi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaomoi
        // TODO add your handling code here:
        dsGioHang.clear();
        defaultGioTable.setRowCount(0);
        count = 0;
        indexGiohang = -1;
        HienThiGio(dsGioHang);
    }//GEN-LAST:event_btTaomoi

    private void btBorakhoigio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorakhoigio
        // TODO add your handling code here:
        if (indexGiohang != -1) {
            String ms = String.valueOf(tbGio.getValueAt(indexGiohang, 0));
            dsGioHang.remove(ms);
            count--;
            HienThiGio(dsGioHang);
            indexGiohang = -1;
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn sách");
        }

    }//GEN-LAST:event_btBorakhoigio
    private void HienThiGio(Hashtable<String, GioHang> gio1) {
        defaultGioTable.setRowCount(0);
        Enumeration<String> enu = gio1.keys();
        while (enu.hasMoreElements()) {
            String key = enu.nextElement();
            GioHang gh = gio1.get(key);
            defaultGioTable.addRow(new Object[]{gh.getMasach(), gh.getTensach(), gh.getSoluong(), gh.getGia()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTim;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbGio;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txMasach;
    private javax.swing.JTextField txNhaxuatban;
    private javax.swing.JTextField txTacgia;
    private javax.swing.JTextField txTensach;
    private javax.swing.JTextField txTheloai;
    // End of variables declaration//GEN-END:variables
}
