/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlthuvien.view;

import com.qlthuvien.model.GioHang;
import com.qlthuvien.model.NCC;
import com.qlthuvien.model.Sach;
import com.qlthuvien.service.NCCService;
import com.qlthuvien.service.SachService;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLNhapSachJPanel extends javax.swing.JPanel {

    private DefaultTableModel defaultSachTable, defaultGioHangTable;
    private NCCService nccService;
    private SachService sachService;
    private int count,//dem so luong co trong gio hang
            indexSach,//chi so hang khi kich vao gio sách
            indexGioHang;//chi so khi kich chuot vao gio hang
    private static NCC ncc;

    public static NCC getNCC() {
        return ncc;
    }
    private static Hashtable<String, GioHang> dsGioHang;

    public static Hashtable<String, GioHang> getGioHang() {
        return dsGioHang;
    }

    public QLNhapSachJPanel() {
        initComponents();
        nccService = new NCCService();
        sachService = new SachService();
        lammoi();
    }

    public void lammoi() {
        jPanelThemSach.setVisible(false);
        count = 0;
        indexGioHang = -1;
        indexSach = -1;
        ncc = new NCC();
        dsGioHang = new Hashtable<String, GioHang>();
        KhoitaoSachTable();
        KhoitaoGioHangTable();
        ThemNCCVaoComBoBox(nccService.getNCC());

    }

    public void KhoitaoSachTable() {
        defaultSachTable = new DefaultTableModel();
        SachTable.setModel(defaultSachTable);
        defaultSachTable.addColumn("Mã sách");
        defaultSachTable.addColumn("Tên sách");
        defaultSachTable.addColumn("Tác giả");
        defaultSachTable.addColumn("Thể loại");
        defaultSachTable.addColumn("Nhà xuất bản");
        defaultSachTable.addColumn("Giá");
        defaultSachTable.addColumn("Số lượng");
        defaultSachTable.addColumn("Trạng thái");

        SachTable.setDefaultEditor(Object.class, null);
        HienThiSachTable(sachService.getSach());

    }

    private void KhoitaoGioHangTable() {
        defaultGioHangTable = new DefaultTableModel();
        gioHangTable.setModel(defaultGioHangTable);

        defaultGioHangTable.addColumn("Mã sách");
        defaultGioHangTable.addColumn("Tên sách");
        defaultGioHangTable.addColumn("Số Lượng");
        defaultGioHangTable.addColumn("Giá");

    }

    private void HienThiSachTable(List<Sach> list) {
        defaultSachTable.setRowCount(0);
        for (Sach sach : list) {
            defaultSachTable.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTenTacGia(), sach.getTheLoai(), sach.getTenNxb(), sach.getGiaSach(), sach.getSoluong(), (sach.isTrangthai() ? "Sách bán" : "Sách mượn")});
        }
    }

    private void ThemNCCVaoComBoBox(List<NCC> list) {
        jComboBoxNhaCungCap.removeAllItems();
        for (NCC ncc : list) {
            jComboBoxNhaCungCap.addItem(ncc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSlNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaSachNhap = new javax.swing.JTextField();
        btThemSachVaoGio = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        btTim = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTensach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTacgia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTheloai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNhaxuatban = new javax.swing.JTextField();
        btNhapMoiSach = new javax.swing.JButton();
        btLamMoiText = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SachTable = new javax.swing.JTable();
        GioHangJPanel = new javax.swing.JPanel();
        jComboBoxNhaCungCap = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gioHangTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btBoRaKhoiGio = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanelThemSach = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenSachThem = new javax.swing.JTextField();
        txtTacGiaThem = new javax.swing.JTextField();
        txtTheLoaiThem = new javax.swing.JTextField();
        txtGiaSachThem = new javax.swing.JTextField();
        jRadioButtonMuon = new javax.swing.JRadioButton();
        jRadioButtonBan = new javax.swing.JRadioButton();
        btThemSachMoi = new javax.swing.JButton();
        btDongThemSach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMasachThem = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNXBThem = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Số Lượng Nhập");

        jLabel2.setText("Giá Sách Nhập");

        btThemSachVaoGio.setText("Thêm  Vào Giỏ");
        btThemSachVaoGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSachVaoGioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSlNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtGiaSachNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThemSachVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSlNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaSachNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(439, 439, 439))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btThemSachVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Mã Sách");

        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimmasach(evt);
            }
        });

        jLabel6.setText("Tên Sách");

        jLabel7.setText("Tác Giả");

        jLabel5.setText("Thể Loại");

        jLabel8.setText("Nhà Xuất Bản");

        txtNhaxuatban.setToolTipText("");

        btNhapMoiSach.setText("Thêm mới");
        btNhapMoiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapMoiSachActionPerformed(evt);
            }
        });

        btLamMoiText.setText("Làm mới");
        btLamMoiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLamMoiText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNhapMoiSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNhapMoiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btLamMoiText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        SachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SachTable.getTableHeader().setReorderingAllowed(false);
        SachTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SachTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SachTable);

        jLabel12.setText("Nhà Cung Cấp");

        gioHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá nhập"
            }
        ));
        gioHangTable.getTableHeader().setReorderingAllowed(false);
        gioHangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gioHangTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(gioHangTable);

        jButton1.setText("Xong");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Làm mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btBoRaKhoiGio.setText("Bỏ ra");
        btBoRaKhoiGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoRaKhoiGioActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Giỏ hàng");

        javax.swing.GroupLayout GioHangJPanelLayout = new javax.swing.GroupLayout(GioHangJPanel);
        GioHangJPanel.setLayout(GioHangJPanelLayout);
        GioHangJPanelLayout.setHorizontalGroup(
            GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GioHangJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangJPanelLayout.createSequentialGroup()
                                .addComponent(btBoRaKhoiGio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(237, 237, 237)))))
                .addContainerGap())
        );

        GioHangJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBoRaKhoiGio, jButton1, jButton3});

        GioHangJPanelLayout.setVerticalGroup(
            GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GioHangJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GioHangJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBoRaKhoiGio))
                .addContainerGap())
        );

        GioHangJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btBoRaKhoiGio, jButton1, jButton3});

        jLabel14.setText("Trạng Thái");

        jLabel13.setText("Giá Sách");

        jLabel15.setText("Thể Loại");

        jLabel11.setText("Tác giả");
        jLabel11.setPreferredSize(new java.awt.Dimension(49, 16));

        jLabel10.setText("Tên Sách");
        jLabel10.setPreferredSize(new java.awt.Dimension(49, 16));
        jLabel10.setRequestFocusEnabled(false);

        buttonGroup1.add(jRadioButtonMuon);
        jRadioButtonMuon.setText("Mượn");

        buttonGroup1.add(jRadioButtonBan);
        jRadioButtonBan.setText("Bán");

        btThemSachMoi.setText("Thêm");
        btThemSachMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSachMoiActionPerformed(evt);
            }
        });

        btDongThemSach.setText("Đóng");
        btDongThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongThemSachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Thêm sách");

        jLabel9.setText("Mã sách");

        txtMasachThem.setEditable(false);

        jLabel17.setText("Nhà xuất bản");

        javax.swing.GroupLayout jPanelThemSachLayout = new javax.swing.GroupLayout(jPanelThemSach);
        jPanelThemSach.setLayout(jPanelThemSachLayout);
        jPanelThemSachLayout.setHorizontalGroup(
            jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemSachLayout.createSequentialGroup()
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addGap(68, 68, 68)
                        .addComponent(txtMasachThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtTenSachThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtTacGiaThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(41, 41, 41)
                        .addComponent(txtNXBThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtTheLoaiThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtGiaSachThem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonMuon)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButtonBan))
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btDongThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btThemSachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelThemSachLayout.setVerticalGroup(
            jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemSachLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addComponent(txtMasachThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenSachThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTacGiaThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17))
                    .addComponent(txtNXBThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15))
                    .addComponent(txtTheLoaiThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaSachThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemSachLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14))
                    .addComponent(jRadioButtonMuon)
                    .addComponent(jRadioButtonBan))
                .addGap(6, 6, 6)
                .addGroup(jPanelThemSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDongThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThemSachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Danh sách tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GioHangJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(GioHangJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelThemSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemSachVaoGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSachVaoGioActionPerformed
        // TODO add your handling code here:
    if(indexSach>=0){    
        String masach = txtMasach.getText();
        String tenSach = txtTensach.getText();
        String loi = "";
        String pattern = "[^0-9]";
        boolean kiemtra = true;

        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(txtSlNhap.getText());
        if (m.find()) {
            loi += "Số lượng nhập vào là số nguyên\n";
            kiemtra = false;
        }
        if (!Pattern.matches(".+", txtSlNhap.getText())) {
            loi += "Số lượng nhập vào không dược để trống\n";
            kiemtra = false;
        }

        if (!Pattern.matches(".+", txtGiaSachNhap.getText())) {
            loi += "Giá nhập vào không dược để trống\n";
            kiemtra = false;
        }

        pattern = "[^0-9]";
        r = Pattern.compile(pattern);
        m = r.matcher(txtGiaSachNhap.getText());
        if (m.find()) {
            loi += "Giá nhập vào là số nguyên";
            kiemtra = false;
        }

        if (kiemtra == true) {
            int soluong = Integer.parseInt(txtSlNhap.getText());
            float gia = Float.parseFloat(txtGiaSachNhap.getText());

            GioHang gh = new GioHang(masach, tenSach, soluong, gia);
            if (!dsGioHang.containsKey(masach)) {  // kiem tra xem tron gio hang da co sach chua
                count++;
                dsGioHang.put(masach, gh);
                defaultGioHangTable.addRow(new Object[]{gh.getMasach(), gh.getTensach(), gh.getSoluong(), gh.getGia()});
            }
            else{
                JOptionPane.showMessageDialog(null, "Đã tồn tại sách trong giỏ hàng", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, loi, "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    else{
        JOptionPane.showMessageDialog(null, "Chưa chọn sách", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btThemSachVaoGioActionPerformed

    private void btTimmasach(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimmasach
        // TODO add your handling code here:
        String masach = txtMasach.getText();
        String tensach = txtTensach.getText();
        String tentacgia = txtTacgia.getText();
        String tennxb = txtNhaxuatban.getText();
        String theloai = txtTheloai.getText();
        HienThiSachTable(sachService.TimSach(masach, tensach, tentacgia, tennxb, theloai));

    }//GEN-LAST:event_btTimmasach


    private void btNhapMoiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapMoiSachActionPerformed
        // TODO add your handling code here:
        txtMasachThem.setText(sachService.getMaSach());
        jRadioButtonBan.setSelected(true);
        GioHangJPanel.setVisible(false);
        jPanelThemSach.setVisible(true);
    }//GEN-LAST:event_btNhapMoiSachActionPerformed

    private void btThemSachMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSachMoiActionPerformed
        // TODO add your handling code here:
        String masach = txtMasachThem.getText();
        String tensach = txtTenSachThem.getText();
        String tentacgia = txtTacGiaThem.getText();
        String tennxb = txtNXBThem.getText();
        String theloai = txtTheLoaiThem.getText();

        String loi = "";
        boolean kiemtra = true;

        if (!Pattern.matches(".+", tensach)) {
            loi += "Tên sách không dược để trống\n";
            kiemtra = false;
        }
        if (!Pattern.matches(".+", tentacgia)) {
            loi += "Tên tác giả không dược để trống\n";
            kiemtra = false;
        }
        if (!Pattern.matches(".+", tennxb)) {
            loi += "Tên nhà xuất bản không dược để trống\n";
            kiemtra = false;
        }
        if (!Pattern.matches(".+", theloai)) {
            loi += "Thể loại không dược để trống\n";
            kiemtra = false;
        }
        if (!Pattern.matches(".+", txtGiaSachThem.getText())) {
            loi += "Giá nhập vào không dược để trống\n";
            kiemtra = false;
        }

        String pattern = "[^0-9]";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(txtGiaSachThem.getText());
        if (m.find()) {
            loi += "Giá nhập vào là số nguyên";
            kiemtra = false;
        }

        if (kiemtra == true) {
            int soluong = 0;
            float giasach = Float.parseFloat(txtGiaSachThem.getText());
            boolean trangthai = true;
            if (jRadioButtonMuon.isSelected()) {
                trangthai = false;
            }
            //  float giaSach, String theLoai, boolean trangthai, int soluong
            
            Sach sach = new Sach(masach, tensach, tentacgia, tennxb, giasach, theloai, trangthai, soluong);
            sachService.ThemSach(sach);
            ClearTextThemMoi();
            jPanelThemSach.setVisible(false);
            GioHangJPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, loi, "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        KhoitaoSachTable();
    }//GEN-LAST:event_btThemSachMoiActionPerformed
    private void ClearTextThemMoi() {
        txtMasachThem.setText("");
        txtTenSachThem.setText("");
        txtTacGiaThem.setText("");
        txtNXBThem.setText("");
        txtTheLoaiThem.setText("");
        txtGiaSachThem.setText("");

    }
    private void btDongThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongThemSachActionPerformed
        // TODO add your handling code here:
        jPanelThemSach.setVisible(false);
        GioHangJPanel.setVisible(true);
    }//GEN-LAST:event_btDongThemSachActionPerformed

    private void SachTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SachTableMouseClicked
        // TODO add your handling code here:
        indexSach = SachTable.getSelectedRow();

        txtSlNhap.setText("");
        txtGiaSachNhap.setText("");
        txtMasach.setText(String.valueOf(SachTable.getValueAt(indexSach, 0)));
        txtTensach.setText(String.valueOf(SachTable.getValueAt(indexSach, 1)));
        txtTacgia.setText(String.valueOf(SachTable.getValueAt(indexSach, 2)));
        txtTheloai.setText(String.valueOf(SachTable.getValueAt(indexSach, 3)));
        txtNhaxuatban.setText(String.valueOf(SachTable.getValueAt(indexSach, 4)));

        KhoaTextField();


    }//GEN-LAST:event_SachTableMouseClicked

    private void btLamMoiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiTextActionPerformed
        // TODO add your handling code here:
        txtMasach.setText("");
        txtTensach.setText("");
        txtTacgia.setText("");
        txtNhaxuatban.setText("");
        txtTheloai.setText("");
        txtSlNhap.setText("");
        txtGiaSachNhap.setText("");
        indexSach = -1;
        MoTextField();
        HienThiSachTable(sachService.getSach());

    }//GEN-LAST:event_btLamMoiTextActionPerformed

    private void btBoRaKhoiGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoRaKhoiGioActionPerformed
        // TODO add your handling code here:

        if (indexGioHang >= 0) {
            String masach = String.valueOf(gioHangTable.getValueAt(indexGioHang, 0));

            dsGioHang.remove(masach);
            count--;
            HienThiGioHang(dsGioHang);
            indexGioHang = -1;
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn sách cần bỏ ra", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btBoRaKhoiGioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dsGioHang.clear();
        count = 0;
        defaultGioHangTable.setRowCount(0);
        ThemNCCVaoComBoBox(nccService.getNCC());
        HienThiGioHang(dsGioHang);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (count > 0) {
            ncc = (NCC) jComboBoxNhaCungCap.getSelectedItem();
            XacNhanNhapSachJFrame xn = new XacNhanNhapSachJFrame();
            xn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            xn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Giỏ hàng chưa có sách", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KhoaTextField() {
        txtMasach.setEditable(false);
        txtTensach.setEditable(false);
        txtTacgia.setEditable(false);
        txtTheloai.setEditable(false);
        txtNhaxuatban.setEditable(false);
    }

    private void MoTextField() {
        txtMasach.setEditable(true);
        txtTensach.setEditable(true);
        txtTacgia.setEditable(true);
        txtTheloai.setEditable(true);
        txtNhaxuatban.setEditable(true);
    }

    private void gioHangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioHangTableMouseClicked
        // TODO add your handling code here:
        indexGioHang = gioHangTable.getSelectedRow();
    }//GEN-LAST:event_gioHangTableMouseClicked
    private void HienThiGioHang(Hashtable<String, GioHang> list) {
        defaultGioHangTable.setRowCount(0);
        Enumeration<String> enu = dsGioHang.keys();
        while (enu.hasMoreElements()) {
            String key = enu.nextElement();
            GioHang gh = dsGioHang.get(key);
            defaultGioHangTable.addRow(new Object[]{gh.getMasach(), gh.getTensach(), gh.getSoluong(), gh.getGia()});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GioHangJPanel;
    private javax.swing.JTable SachTable;
    private javax.swing.JButton btBoRaKhoiGio;
    private javax.swing.JButton btDongThemSach;
    private javax.swing.JButton btLamMoiText;
    private javax.swing.JButton btNhapMoiSach;
    private javax.swing.JButton btThemSachMoi;
    private javax.swing.JButton btThemSachVaoGio;
    private javax.swing.JButton btTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable gioHangTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<NCC> jComboBoxNhaCungCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelThemSach;
    private javax.swing.JRadioButton jRadioButtonBan;
    private javax.swing.JRadioButton jRadioButtonMuon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtGiaSachNhap;
    private javax.swing.JTextField txtGiaSachThem;
    private javax.swing.JTextField txtMasach;
    private javax.swing.JTextField txtMasachThem;
    private javax.swing.JTextField txtNXBThem;
    private javax.swing.JTextField txtNhaxuatban;
    private javax.swing.JTextField txtSlNhap;
    private javax.swing.JTextField txtTacGiaThem;
    private javax.swing.JTextField txtTacgia;
    private javax.swing.JTextField txtTenSachThem;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTheLoaiThem;
    private javax.swing.JTextField txtTheloai;
    // End of variables declaration//GEN-END:variables
}
