/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlthuvien.view;

import com.qlthuvien.model.GioHang;
import com.qlthuvien.model.NCC;
import com.qlthuvien.model.PhieuNhap;
import com.qlthuvien.service.ChiTietNhapService;
import com.qlthuvien.service.PhieuNhapService;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class XacNhanNhapSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form XacNhanNhapSachJFrame
     */
    private DefaultTableModel defaultGioHangTable;
    private static boolean check = false;
    private float tong = 0;
    private PhieuNhapService phieuNhapService;
    private ChiTietNhapService chiTietNhapService;
    private NCC ncc;
    public XacNhanNhapSachJFrame() {
        initComponents();
        phieuNhapService = new PhieuNhapService();
        chiTietNhapService = new ChiTietNhapService();
        //Tu dong dien ngay
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        txtNgayMua.setText(String.valueOf(ft.format(dNow)));
        
        //Tu dong dien maPN
        txtMaPN.setText(phieuNhapService.getMaPhieuNhap());
        //Tu dong dien maNCC,tenNCC
        ncc = QLNhapSachJPanel.getNCC();
        txtMaNCC.setText(ncc.getMaNCC());
        txtTenNCC.setText(ncc.getTenNCC());
        
        
        HienThiTable();
    }
    private void HienThiTable() {
        defaultGioHangTable = new DefaultTableModel();

        dsMua.setModel(defaultGioHangTable);

        defaultGioHangTable.addColumn("Ma sach");
        defaultGioHangTable.addColumn("Ten sach");
        defaultGioHangTable.addColumn("So luong");
        defaultGioHangTable.addColumn("Gia");

        Hashtable<String, GioHang> listGioHang = QLNhapSachJPanel.getGioHang();

        Enumeration<String> enu = listGioHang.keys();
        while (enu.hasMoreElements()) {
            String key = enu.nextElement();
            GioHang gioHang = listGioHang.get(key);

            defaultGioHangTable.addRow(new Object[]{gioHang.getMasach(), gioHang.getTensach(), String.valueOf(gioHang.getSoluong()), String.valueOf(gioHang.getGia())});

            tong += gioHang.getSoluong() * gioHang.getGia();

        }

        txtTongTien.setText("" + tong);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsMua = new javax.swing.JTable();
        labeltongtien = new javax.swing.JLabel();
        btXong = new javax.swing.JButton();
        txtMaPN = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JLabel();
        txtNgayMua = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Phiếu Nhập Sách");

        jLabel2.setText("Nhà cung cấp");

        jLabel4.setText("Mã Phiếu Mua");

        jLabel3.setText("Ngày Mua");

        jLabel5.setText("Danh Sách Sách Nhập");

        dsMua.setAutoCreateRowSorter(true);
        dsMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsMua.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(dsMua);

        labeltongtien.setText("Tổng Thanh Toán");

        btXong.setText("Xong");
        btXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXongActionPerformed(evt);
            }
        });

        txtMaPN.setText(" ");

        txtTongTien.setText("  ");

        txtTenNCC.setText("jLabel6");

        txtNgayMua.setText("jLabel7");

        jLabel7.setText("Mã Nhà Cung Cấp");

        txtMaNCC.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(txtTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeltongtien)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(168, 168, 168)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtNgayMua, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btXong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 83, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaNCC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayMua)
                    .addComponent(jLabel4)
                    .addComponent(txtMaPN))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltongtien)
                    .addComponent(txtTongTien))
                .addGap(18, 18, 18)
                .addComponent(btXong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXongActionPerformed
        // TODO add your handling code here:

        String mapn = txtMaPN.getText();
        String maNCC = txtMaNCC.getText();
        float tongtien = Float.parseFloat(txtTongTien.getText());

        PhieuNhap pn = new PhieuNhap(mapn,"", maNCC, tongtien);
        //Them phieu mua
        phieuNhapService.themPhieuNhap(pn);

        //Them chi tiet phieu mua
        Hashtable<String, GioHang> listGioHang = QLNhapSachJPanel.getGioHang();
        chiTietNhapService.themChiTietNhap(listGioHang, mapn);  
        check = true;
        
        
        //Dong JFrame nay  lai
        this.dispose();        

    }//GEN-LAST:event_btXongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhanNhapSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhanNhapSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhanNhapSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhanNhapSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhanNhapSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btXong;
    private javax.swing.JTable dsMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeltongtien;
    private javax.swing.JLabel txtMaNCC;
    private javax.swing.JLabel txtMaPN;
    private javax.swing.JLabel txtNgayMua;
    private javax.swing.JLabel txtTenNCC;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}
